[build]
  base = "client"               # <-- Netlify will start inside /client
  command = "npm run build"     # <-- no need to cd
  publish = ".netlify/output"   # <-- plugin handles Next.js output

[[plugins]]
  package = "@netlify/plugin-nextjs"
