[build]
  base = "client"            # start inside the client folder
  command = "npm run build"  # build command
  # publish = ".netlify/output"  <-- REMOVE this line

[[plugins]]
  package = "@netlify/plugin-nextjs"
