import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.",
    price: 1199,
    originalPrice: 1299,
    category: "smartphones",
    brand: "Apple",
    image: "/iphone-15-pro-max-titanium.png",
    images: ["/iphone-15-pro-max-front-view.jpg", "/iphone-15-pro-max-back-view.jpg", "/iphone-15-pro-max-camera-detail.jpg"],
    inStock: true,
    rating: 4.8,
    reviewCount: 2847,
    specs: {
      Display: '6.7" Super Retina XDR',
      Chip: "A17 Pro",
      Camera: "48MP Main + 12MP Ultra Wide",
      Storage: "256GB",
      Battery: "Up to 29 hours video playback",
    },
    featured: true,
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    description: "Premium Android flagship with S Pen, 200MP camera, and AI-powered features.",
    price: 1299,
    category: "smartphones",
    brand: "Samsung",
    image: "/samsung-galaxy-s24-ultra.png",
    images: ["/samsung-galaxy-s24-ultra-front.jpg", "/samsung-galaxy-s24-ultra-with-s-pen.jpg"],
    inStock: true,
    rating: 4.7,
    reviewCount: 1923,
    specs: {
      Display: '6.8" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 3",
      Camera: "200MP Main + 50MP Telephoto",
      Storage: "512GB",
      Battery: "5000mAh",
    },
    featured: true,
  },
  {
    id: "3",
    name: 'MacBook Pro 16"',
    description: "Supercharged by M3 Max chip for extreme performance and all-day battery life.",
    price: 2499,
    originalPrice: 2699,
    category: "laptops",
    brand: "Apple",
    image: "/macbook-pro-16-inch-m3-max.jpg",
    images: ["/macbook-pro-16-open-front-view.jpg", "/macbook-pro-16-side-view.jpg"],
    inStock: true,
    rating: 4.9,
    reviewCount: 1456,
    specs: {
      Display: '16.2" Liquid Retina XDR',
      Chip: "Apple M3 Max",
      Memory: "36GB Unified Memory",
      Storage: "1TB SSD",
      Battery: "Up to 22 hours",
    },
    featured: true,
  },
  {
    id: "4",
    name: "Dell XPS 15",
    description: "Premium Windows laptop with stunning OLED display and powerful Intel performance.",
    price: 1899,
    category: "laptops",
    brand: "Dell",
    image: "/dell-xps-15-laptop.jpg",
    images: ["/dell-xps-15-open.jpg", "/dell-xps-15-keyboard-detail.jpg"],
    inStock: true,
    rating: 4.6,
    reviewCount: 892,
    specs: {
      Display: '15.6" OLED 3.5K',
      Processor: "Intel Core i7-13700H",
      Memory: "32GB DDR5",
      Storage: "1TB NVMe SSD",
      Graphics: "NVIDIA RTX 4060",
    },
  },
  {
    id: "5",
    name: 'iPad Pro 12.9"',
    description: "Ultimate iPad experience with M2 chip, Liquid Retina XDR display, and Apple Pencil support.",
    price: 1099,
    category: "tablets",
    brand: "Apple",
    image: "/ipad-pro-12-9-inch.png",
    images: ["/ipad-pro-front-view.jpg", "/ipad-pro-with-apple-pencil.jpg"],
    inStock: true,
    rating: 4.8,
    reviewCount: 1234,
    specs: {
      Display: '12.9" Liquid Retina XDR',
      Chip: "Apple M2",
      Storage: "256GB",
      Camera: "12MP Wide + 10MP Ultra Wide",
      Connectivity: "Wi-Fi 6E + 5G",
    },
    featured: true,
  },
  {
    id: "6",
    name: "Samsung Galaxy Tab S9+",
    description: "Premium Android tablet with Dynamic AMOLED display and S Pen included.",
    price: 899,
    category: "tablets",
    brand: "Samsung",
    image: "/samsung-galaxy-tab-s9-plus.jpg",
    images: ["/galaxy-tab-s9-plus-front.jpg", "/galaxy-tab-s9-plus-with-s-pen.jpg"],
    inStock: true,
    rating: 4.5,
    reviewCount: 678,
    specs: {
      Display: '12.4" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 2",
      Memory: "12GB RAM",
      Storage: "256GB",
      Battery: "10,090mAh",
    },
  },
  {
    id: "7",
    name: "AirPods Pro (2nd Gen)",
    description: "Active Noise Cancellation, Adaptive Audio, and personalized spatial audio.",
    price: 249,
    category: "accessories",
    brand: "Apple",
    image: "/airpods-pro-2nd-generation.jpg",
    images: ["/airpods-pro-with-case.jpg", "/airpods-pro-earbuds-closeup.jpg"],
    inStock: true,
    rating: 4.7,
    reviewCount: 3421,
    specs: {
      "Noise Cancellation": "Active Noise Cancellation",
      Battery: "Up to 6 hours listening time",
      Chip: "Apple H2",
      Connectivity: "Bluetooth 5.3",
      "Water Resistance": "IPX4",
    },
  },
  {
    id: "8",
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling headphones with exceptional sound quality.",
    price: 399,
    category: "accessories",
    brand: "Sony",
    image: "/sony-wh-1000xm5.png",
    images: ["/sony-wh-1000xm5-side-view.jpg", "/sony-wh-1000xm5-folded.jpg"],
    inStock: true,
    rating: 4.8,
    reviewCount: 2156,
    specs: {
      "Noise Cancellation": "Industry-leading ANC",
      Battery: "Up to 30 hours",
      Driver: "30mm",
      Connectivity: "Bluetooth 5.2, LDAC",
      Weight: "250g",
    },
  },
  {
    id: "9",
    name: "Google Pixel 8 Pro",
    description: "Google AI-powered smartphone with exceptional camera and pure Android experience.",
    price: 999,
    category: "smartphones",
    brand: "Google",
    image: "/google-pixel-8-pro.png",
    images: ["/google-pixel-8-pro-front.jpg", "/google-pixel-8-pro-camera-bar.jpg"],
    inStock: true,
    rating: 4.6,
    reviewCount: 1567,
    specs: {
      Display: '6.7" LTPO OLED',
      Chip: "Google Tensor G3",
      Camera: "50MP Main + 48MP Telephoto",
      Storage: "256GB",
      Battery: "5050mAh",
    },
  },
  {
    id: "10",
    name: "Lenovo ThinkPad X1 Carbon",
    description: "Business ultrabook with legendary keyboard, military-grade durability, and all-day battery.",
    price: 1699,
    category: "laptops",
    brand: "Lenovo",
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    inStock: true,
    rating: 4.7,
    reviewCount: 743,
    specs: {
      Display: '14" WUXGA IPS',
      Processor: "Intel Core i7-1365U",
      Memory: "16GB LPDDR5",
      Storage: "512GB SSD",
      Weight: "1.12kg",
    },
  },
  {
    id: "11",
    name: "Magic Keyboard for iPad Pro",
    description: "Premium keyboard with trackpad, backlit keys, and floating design for iPad Pro.",
    price: 349,
    category: "accessories",
    brand: "Apple",
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    inStock: true,
    rating: 4.5,
    reviewCount: 892,
    specs: {
      Compatibility: 'iPad Pro 12.9" (3rd-6th gen)',
      "Backlit Keys": "Yes",
      Trackpad: "Multi-Touch",
      "USB-C": "Pass-through charging",
      Weight: "710g",
    },
  },
  {
    id: "12",
    name: "Samsung 45W USB-C Charger",
    description: "Super fast charging for Samsung devices and other USB-C compatible electronics.",
    price: 49,
    category: "accessories",
    brand: "Samsung",
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    inStock: true,
    rating: 4.4,
    reviewCount: 1234,
    specs: {
      "Power Output": "45W",
      Port: "USB-C",
      Cable: "USB-C to USB-C included",
      "Fast Charging": "Super Fast Charging 2.0",
      Compatibility: "Universal USB-C",
    },
  },
]

export const categories = [
  { id: "all", name: "All Products", count: products.length },
  { id: "smartphones", name: "Smartphones", count: products.filter((p) => p.category === "smartphones").length },
  { id: "laptops", name: "Laptops", count: products.filter((p) => p.category === "laptops").length },
  { id: "tablets", name: "Tablets", count: products.filter((p) => p.category === "tablets").length },
  { id: "accessories", name: "Accessories", count: products.filter((p) => p.category === "accessories").length },
]

export const brands = ["Apple", "Samsung", "Google", "Dell", "Lenovo", "Sony"]
